import 'dart:async';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:devup/model/user.dart';
import 'package:firestore_helpers/firestore_helpers.dart';
import 'package:shared_preferences/shared_preferences.dart';


////////////////////////////////////////////////////////////////////////////////////
/// IMPORTANT: All objects contain there documentID as property.
/// This ID is generated by the App, not be FireStore. If objects have unique names
/// like categories that name is used as key. Otherwise a UUID is generated
////////////////////////////////////////////////////////////////////////////////////


class ObjectDoesNotExistsException implements Exception
{
  final String message;

  
    ObjectDoesNotExistsException(this.message);
  
  @override
  String toString() {
      return message;
    }

}


abstract class DatabaseService {
  User currentUser;

  Future<bool> updateUser(User user);

  Future<User> getCurrentUser();
}

class DatabaseServiceFireStore implements DatabaseService {

  final userCollection = Firestore.instance.collection("users");


  ////////////////////////////////////////////////////////////////////////////////////
  /// Users
  ///////////////////////////////////////////////////////////////////////////////////

  @override
  Future<bool> updateUser(User user) async {
    try {
      await userCollection.document(user.id).setData(user.toJson());
      return true;
    } catch (e) {
      print(e);
      //todo logging
      return false;
    }
  }

  @override
  User currentUser;

  @override
  Future<User> getCurrentUser() async {
    if (currentUser == null)
    {
      SharedPreferences prefs = await SharedPreferences.getInstance();
    }
    return null;
  }

    
  }

